Feature/sns
wecode-bootcamp-korea/10-Oh29-ya-backend pull request #10
Opened 2020-07-28 12:07 UTC by minho-lee0716

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
2tv 브랜치에서 user로 인해 구현하지 못한 엔드포인트를 구현할 branch 입니다.
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요)
0728.21:05 > 일단 master를 pull 하였고, 원래 feature/29tv에서
구현하지 못한 기능(유저관련 좋아요 등)을 구현할 예정.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-07-29 01:54 UTC, evergreen-david requested changes

2020-07-29 01:54 UTC, evergreen-david commented on product/models.py
> +    desc           = models.CharField(max_length = 300)
```suggestion
    description           = models.CharField(max_length = 300)
```

2020-07-29 01:54 UTC, evergreen-david commented on product/models.py
> +    brand_category = models.ManyToManyField('Category',through='BrandCategory' )
```suggestion
    brand_category = models.ManyToManyField('Category', through='BrandCategory')   
```

2020-07-29 01:54 UTC, evergreen-david commented on product/models.py
> +    category_subcategory = models.ManyToManyField('Subcategory',through='CategorySubcategory')
```suggestion
    subcategory = models.ManyToManyField('Subcategory', through='CategorySubcategory')
```

2020-07-29 01:54 UTC, evergreen-david commented on product/urls.py
>      path('/specialorders',SpecialOrderView.as_view())
```suggestion
    path('/special-orders', SpecialOrderView.as_view())
```

2020-07-29 01:54 UTC, evergreen-david commented on product/views.py
> +            product = Product.objects.prefetch_related('image_set').select_related('category').select_related('brand').select_related('subcategory').select_related('detail').get(id=product_id)
select_related 에 여러인자 넣어서 정리 해주세요!
만약 타고타고 가는거면 더블 언더스코어 사용해보기 바랍니다.

2020-07-29 01:54 UTC, evergreen-david commented on product/views.py
> +            return JsonResponse({'message':"VALUEERROR"}, status = 400)
```suggestion
            return JsonResponse({'message':"VALUE_ERROR"}, status = 400)
```

2020-07-29 01:54 UTC, evergreen-david commented on sns/models.py
> +    like = models.ManyToManyField(User, through = 'LikePost')
= align 맞춰주세요!

2020-07-29 02:10 UTC, minho-lee0716 commented on product/models.py
> +    desc           = models.CharField(max_length = 300)
Done!

2020-07-29 02:11 UTC, minho-lee0716 commented on product/models.py
> +    category_subcategory = models.ManyToManyField('Subcategory',through='CategorySubcategory')
Done!

2020-07-29 02:12 UTC, minho-lee0716 commented on product/urls.py
>      path('/specialorders',SpecialOrderView.as_view())
Done!

2020-07-29 02:36 UTC, minho-lee0716 commented on product/views.py
> +            product = Product.objects.prefetch_related('image_set').select_related('category').select_related('brand').select_related('subcategory').select_related('detail').get(id=product_id)
정리했습니다!

2020-07-30 02:55 UTC, soheon-lee commented on mypage/views.py
> +                'user_likes_pressed' : (True if LikeProduct.objects.filter(user_id=User.objects.get(id=user.id).id, product_id=Product.objects.get(id=word.product.id).id).exists() else False)
이미 `user.id`값을 가지고 있기 때문에 LikeProduct를 get 해오실 때, User객체를 id를 기준으로 `get`하고 다시 `id`속성에 접근 하시지 않으셔도 됩니다. Product도 마찬가지입니다.

2020-07-30 02:55 UTC, soheon-lee commented on mypage/views.py
> +post_id=Post.objects.get(id=post.post.id).id).exists() else False)
이미 user.id값을 가지고 있기 때문에 LikeProduct를 get 해오실 때, User객체를 id를 기준으로 get하고 다시 id속성에 접근 하시지 않으셔도 됩니다. Product도 마찬가지입니다.

2020-07-30 03:24 UTC, minho-lee0716 commented on mypage/views.py
> +                'user_likes_pressed' : (True if LikeProduct.objects.filter(user_id=User.objects.get(id=user.id).id, product_id=Product.objects.get(id=word.product.id).id).exists() else False)
이해 했슴다~

2020-07-30 03:25 UTC, minho-lee0716 commented on mypage/views.py
> +post_id=Post.objects.get(id=post.post.id).id).exists() else False)
이것도 수정하였습니다~

2020-07-30 12:40 UTC, soheon-lee commented on mypage/views.py
> +            user_likes = User.objects.prefetch_related('likepost_set').get(id=user.id).likepost_set.all()
토큰에서 이미 `User`객체를 반환하였기 때문에, 그 User 의 id를 가지고 다시 동일한 User 객체를 찾아오고 있습니다. 토큰에서 받아온 User객체인 `user`의 `id`를 바로 이용해보세요 :)

2020-07-30 12:40 UTC, soheon-lee commented on mypage/views.py
> +            return JsonResponse({'message':e}, status = 200)
`error` 반환하실 때 status code는 200이 아닙니다. 적절한 status code를 사용해주세요.

2020-07-30 12:40 UTC, soheon-lee commented on product/views.py
> +            products            = product.filter(category=Category.objects.get(name=data["category"]),
- `product`와 `products`를 두 줄로 분리하신 이유가 있나요?
- 카테고리의 이름이 있다면 `category__name`을 활용해서 필터링해보세요

2020-07-30 12:40 UTC, soheon-lee commented on product/views.py
> +                                                           product = Product.objects.get(id = temp['id'])).exists() else False)
- `temp`와 같이 그 의미를 알 수 없는 변수명은 사용하지 않습니다. 제품을 뜻하는 변수라면 product로 변경해주세요.
- LikeProduct를 필터링할 때 user객체의 id를 이미 아는 상황이라면 `user_id`와 `product.id`를 바로 사용하시면 됩니다. 불필요한 get( )메소드를 사용하고 계십니다.

2020-07-30 12:40 UTC, soheon-lee commented on product/views.py
> +                       True if LikeProduct.objects.filter(user_id=User.objects.get(id=user.id).id,
LikeProduct를 필터링할 때 user객체의 id를 이미 아는 상황이라면 user_id와 product.id를 바로 사용하시면 됩니다. 불필요한 get( )메소드를 사용하고 계십니다.

2020-07-30 12:40 UTC, soheon-lee commented on product/views.py
> +                        True if LikeProduct.objects.filter(user_id=User.objects.get(id=user.id).id,
LikeProduct를 필터링할 때 user객체의 id를 이미 아는 상황이라면 user_id와 product.id를 바로 사용하시면 됩니다. 불필요한 get( )메소드를 사용하고 계십니다.

2020-07-30 13:42 UTC, minho-lee0716 commented on mypage/views.py
> +            user_likes = User.objects.prefetch_related('likepost_set').get(id=user.id).likepost_set.all()
쎈스있게 바꿔줬고 한줄이라도 줄이기 위해 바로 리스트 컴플리헨션에 넣어 줬습니다

2020-07-31 01:15 UTC, minho-lee0716 commented on mypage/views.py
> +            return JsonResponse({'message':e}, status = 200)
확인했습니다~

2020-07-31 01:22 UTC, minho-lee0716 commented on product/views.py
> +                                                           product = Product.objects.get(id = temp['id'])).exists() else False)
product로 바꿔주었고, user와 리스트 컴플리헨션의 product로 가져 왔습니다~

2020-07-31 01:33 UTC, minho-lee0716 commented on product/views.py
> +                       True if LikeProduct.objects.filter(user_id=User.objects.get(id=user.id).id,
완료했습니다!

2020-07-31 01:36 UTC, minho-lee0716 commented on product/views.py
> +                        True if LikeProduct.objects.filter(user_id=User.objects.get(id=user.id).id,
수정 완료했습니다

2020-07-31 01:47 UTC, minho-lee0716 commented on product/views.py
> +            products            = product.filter(category=Category.objects.get(name=data["category"]),
1. 너무 길어져서 가독성을 위해 그랬습니다.
2. category, subcategory 모두 __name으로 참조 했습니다.

2020-07-31 01:54 UTC, minho-lee0716 commented on mypage/views.py
> +            user_likes = User.objects.prefetch_related('likepost_set').get(id=user.id).likepost_set.all()
스무스하게 리팩토링 끝났습니다~

2020-07-31 01:58 UTC, minho-lee0716 commented
수정 엔드포인트 모두 postman으로 점검까지 완료했습니다

2020-07-31 02:00 UTC, merged