add signup & signin feature
wecode-bootcamp-korea/10-Oh29-ya-backend pull request #2
Opened 2020-07-21 04:45 UTC by bangjom

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
로그인, 회원가입 엔드포인트 구현      
         
		 
## 수정 사항들 자세한 내용

이메일 이메일 형식
비밀번호 최소 8자리, 최소 1개의 문자, 1개의 숫자

회원가입 or 로그인시 토큰 발급

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [v] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [v] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [v] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [v] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-07-24 02:15 UTC, soheon-lee commented on account/models.py
> +
쓰이지 않은 공백 제거해주세요 :)

2020-07-24 02:15 UTC, soheon-lee commented on account/views.py
> +from django.views import View
`import` 기준으로 코드 간격 맞춰주세요

2020-07-24 02:15 UTC, soheon-lee commented on account/views.py
> +        password_validator  = RegexValidator(regex     =  "^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$")
```suggestion
        password_validator  = RegexValidator(regex = "^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$")             
```

2020-07-24 02:15 UTC, soheon-lee commented on account/views.py
> +            return JsonResponse({'message': 'EMAIL WHICH IS EXISTED'},status=401)
```suggestion
            return JsonResponse({'message': 'EXISTING_EMAIL'},status=401)
```

2020-07-24 02:15 UTC, soheon-lee commented on account/views.py
> +            return JsonResponse({'message':'WRONG_EMAIL'},status=400)
이메일이 틀린건지 비밀번호를 틀린건지 명확하게 안내해주면 보안상 위험이 있습니다. 두 경우의 메세지를 똑같이 통일해주세요.

2020-07-24 02:15 UTC, soheon-lee commented on account/views.py
> +            return JsonResponse({'message':'INVALID_EMAIL_FORMAT'},status=400)
```suggestion
            return JsonResponse({'message':'INVALID_EMAIL'},status=400)
```

2020-07-24 02:15 UTC, soheon-lee commented on config/urls.py
> +from django.urls import path,include
```suggestion
from django.urls import (
    path,
    include
)
```
같은 줄에서 import 하고자 하는 것이 두가지 이상일 때, 개별 줄로 분리해주는 것이 위코드 코딩 컨벤션입니다 :)

2020-07-24 06:54 UTC, evergreen-david requested changes

2020-07-24 06:54 UTC, evergreen-david commented on account/tests.py
> +# Create your tests here.
회원가입, 로그인 각각 성공하는 케이스1개씩 유닛 테스트 구현 부탁 드립니다.

2020-07-27 02:24 UTC, evergreen-david requested changes

2020-07-27 02:24 UTC, evergreen-david commented on db_uploader.py
> +import os
csv 는 올리지 말고 삭제하고 정리 부탁 드립니다.
gitignore에도 추가해주세요.!

2020-07-27 02:24 UTC, evergreen-david commented on product/models.py
> +
공백은 한줄만 띄워지도록 정리 부탁 드려요.

2020-07-27 02:24 UTC, evergreen-david commented on product/models.py
> +
여기도 동일한 커멘트 입니다.

2020-07-27 02:24 UTC, evergreen-david commented on product/views.py
> +from .models import *
import *는 실제 코드에서는 사용하면 안됩니다. 왜냐하면 import 쓰지않는 모듈도 임포트 될 수 있기 때문입니다. 정리해주세요.!

2020-07-27 02:24 UTC, evergreen-david commented on product/views.py
> +        product=Product.objects
```suggestion
        product = Product.objects
```

2020-07-27 02:24 UTC, evergreen-david commented on product/views.py
> +    # get메소드를 사용하고 싶지만 프론트에서 get으로 데이터 주는 방법을 몰라 임시방편으로 post 로 바꿈
임시방편으로 구현하기 보다는 데이터를 fetch 하는것은 get메소드를 사용해야하는데 쿼리스트링으로 구현해서 테스트 부탁 드립니다.

2020-07-28 06:31 UTC, closed without merging

2020-07-28 06:32 UTC, bangjom commented
다시 파겠습니다 죄송합니다