Feature/29tv
wecode-bootcamp-korea/10-Oh29-ya-backend pull request #3
Opened 2020-07-21 16:25 UTC by minho-lee0716

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요. 예: 로그인 엔드포인트 구현)
Aquery 모델링을 바탕으로 29tv 라는 앱을 만들어 models.py 파일을 작성하였습닙다. 
         
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요)
1️⃣ 아직 User에 관한 models.py 파일이 완성되지 않아서 관련 import, class 등
모두 주석처리를 해주었습니다.
(위코드 스타일을 알지만 잠시만 주석처리를 해놓겠습니다.)

2️⃣ makemigrations / migrate 모두 이상 없이 완료 하였습니다.
가짜 데이터로 db 테스트 완료했습니다. 크롤링 진행하겠습니다.

3️⃣ config/settings.py 파일에는 29tv라는 앱을 등록해 주었습니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ V ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ V ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ V ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ V ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-07-24 02:29 UTC, soheon-lee commented on config/urls.py
> +from django.urls import path, include
```suggestion
from django.urls import (
    path, 
    include
)
```
한 줄에서 import 하고자 하는 대상이 두 개 이상일 경우 개별 줄로 분리해주는 것이 위코드 코딩 컨벤션입니다 :-)

2020-07-24 02:29 UTC, soheon-lee commented on sns/views.py
> +from .models import Staff, Post, Hashtag, PostHashtag
한 줄에서 import 하고자 하는 대상이 두 개 이상일 경우 개별 줄로 분리해주는 것이 위코드 코딩 컨벤션입니다 :-)

2020-07-24 02:29 UTC, soheon-lee commented on sns/views.py
> +from django.shortcuts import render
사용하지 않는 코드입니다. 제거해주세요

2020-07-24 02:29 UTC, soheon-lee commented on sns/views.py
> +                hashtag_list = []
코드 간격 `=`을 기준으로 정렬해주세요.

2020-07-24 02:29 UTC, soheon-lee commented on sns/views.py
> +                    'hashtag':hashtag_list
코드 간격 `:`을 기준으로 정렬해주세요.

2020-07-24 02:29 UTC, soheon-lee commented on sns/views.py
> +                center_table_list = list(PostHashtag.objects.filter(posts_id=post.id).values())
`post` 가 `Post` 객체이고 `Post` 클래스는 `PostHashtag`클래스와 이미 연결되어 있습니다. 따라서 PostHashtag 객체에 새로 접근하지 않고, `post`에 연결된 태그 속성으로 바로 접근해보세요 👍

2020-07-24 02:29 UTC, soheon-lee commented on sns/views.py
> +                    hashtag_name = Hashtag.objects.get(id=obj['hashtags_id']).name
Hashtag 또한 마찬가지입니다. `Hashtag` 클래스를 대상으로 get을 하지 않아도 post->posthashtag->hashtag 로 접근해서 가져올 수 있습니다. 상록님의 django query session을 떠올려보세요 :)

2020-07-24 02:29 UTC, soheon-lee commented on sns/views.py
> +                    hashtag_list.append(hashtag_name)
`list comprehension` 사용해보세요

2020-07-24 06:07 UTC, minho-lee0716 commented on config/urls.py
> +from django.urls import path, include
넹

2020-07-24 06:13 UTC, minho-lee0716 commented on sns/views.py
> +from .models import Staff, Post, Hashtag, PostHashtag
넹22

2020-07-24 06:15 UTC, minho-lee0716 commented on sns/views.py
> +from django.shortcuts import render
넹333

2020-07-24 06:16 UTC, minho-lee0716 commented on sns/views.py
> +                hashtag_list = []
큰 실수를 했군요. 시정하겠습니다.

2020-07-24 06:17 UTC, minho-lee0716 commented on sns/views.py
> +                    'hashtag':hashtag_list
넵!

2020-07-24 06:53 UTC, evergreen-david requested changes

2020-07-24 06:53 UTC, evergreen-david commented on sns/models.py
> +#from account.models import User
주석은 정리를 부탁 드립니다.

2020-07-24 06:53 UTC, evergreen-david commented on sns/models.py
> +    #user            = models.ManyToManyField(User, through = 'PostLike')
같은 커멘트 입니다.

2020-07-24 06:53 UTC, evergreen-david commented on sns/models.py
> +'''
정리 부탁 드립니다.

2020-07-24 06:53 UTC, evergreen-david commented on sns/urls.py
> +    path('/recommend', PostView.as_view())
유닛 테스트 성공케이스 한개 구현부탁드립니다.

2020-07-24 12:03 UTC, minho-lee0716 commented on sns/models.py
> +#from account.models import User
넵!

2020-07-24 12:03 UTC, minho-lee0716 commented on sns/models.py
> +    #user            = models.ManyToManyField(User, through = 'PostLike')
넵!22

2020-07-24 12:03 UTC, minho-lee0716 commented on sns/models.py
> +'''
넵!333

2020-07-24 14:14 UTC, minho-lee0716 commented on sns/views.py
> +                center_table_list = list(PostHashtag.objects.filter(posts_id=post.id).values())
했습니다~

2020-07-24 15:44 UTC, minho-lee0716 commented on sns/views.py
> +                    hashtag_name = Hashtag.objects.get(id=obj['hashtags_id']).name
제가 잘못알고있었어요 ㅠㅠ
post.posthashtag_set.hashtag_set 이렇게 하는건줄 알았는데,
post.hashtag_set으로 한번에 참조가 되는군요(삽질 성공)
수정 완료입니다~

2020-07-24 15:45 UTC, minho-lee0716 commented on sns/views.py
> +                    hashtag_list.append(hashtag_name)
수정 완료했습니다!

2020-07-24 15:50 UTC, minho-lee0716 commented on sns/views.py
> +                center_table_list = list(PostHashtag.objects.filter(posts_id=post.id).values())
아 그리고 17번째줄에서 생각해보니 꼭 list가 아니고 Query Set list여도 되는데 쓸데없이 list로 변환해주어서 list는 빼주었습니다~

2020-07-24 16:00 UTC, minho-lee0716 commented on sns/views.py
> +                    hashtag_name = Hashtag.objects.get(id=obj['hashtags_id']).name
post_list 정의 시, .all()이 필요가 없어서 추가로 제거해 주었습니다.

2020-07-27 04:31 UTC, minho-lee0716 commented on sns/urls.py
> +    path('/recommend', PostView.as_view())
유닛 테스트 너무 어려워서 일단 다른거 먼저 진행해보겠습니다 ㅜㅜ

2020-07-27 04:36 UTC, minho-lee0716 commented
현재 유저가 post를 좋아할 수 있게 기능도 추가를 했는데 User가 merge가 안돼서 코드를 올리지 못하는 상황입니다 ㅠ

2020-07-28 06:55 UTC, evergreen-david requested changes

2020-07-28 06:55 UTC, evergreen-david commented on sns/models.py
> +#from account.models import User
주석 정리가 안되었네요 확인 부탁 드립니다.

2020-07-28 06:56 UTC, evergreen-david requested changes

2020-07-28 06:56 UTC, evergreen-david commented on sns/models.py
> +    #user            = models.ManyToManyField(User, through = 'PostLike')
여기도 정리가 안되었네요

2020-07-28 07:12 UTC, evergreen-david requested changes

2020-07-28 07:12 UTC, evergreen-david commented on sns/views.py
> +            for post in post_list:
리스트컴프리헨션으로 수정 부탁 드립니다.

2020-07-28 07:13 UTC, evergreen-david requested changes

2020-07-28 07:13 UTC, evergreen-david commented on sns/views.py
> +                staff_id          = post.staff_id
미사용 변수 삭제 부탁 드립니다.

2020-07-28 07:16 UTC, minho-lee0716 commented on sns/views.py
> +                staff_id          = post.staff_id
삭제 완료했습니다!

2020-07-28 07:52 UTC, minho-lee0716 commented on sns/views.py
> +            for post in post_list:
완벽하게 리스트 컴플리핸션 완료했습니다.

2020-07-28 07:56 UTC, evergreen-david approved these changes

2020-07-28 07:56 UTC, merged